language: java

sudo: false # faster builds

before_script: cd todo-backend

script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then mvn clean install; fi

after_success:
- bash <(curl -s https://codecov.io/bash)