spring:
  profiles: default 

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sampletest;MODE=MySQL

keycloak:
    url: https://keycloak.docker.atosresearch.eu/auth
    realm: kibana
    client_id: kibana
    oauth: true

---
spring:
  profiles: test

spring.jpa:
    hibernate:
      ddl-auto: create-drop

keycloak:
    url: https://keycloak.docker.atosresearch.eu/auth
    realm: kibana
    client_id: kibana
    oauth: false

---
spring:
  profiles: local

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1/sampledev
  username: sample
  password: sample

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update

keycloak:
    url: https://keycloak.docker.atosresearch.eu/auth
    realm: kibana
    client_id: kibana
    oauth: true

