server:
  port: 8081

spring:
  profiles: default 

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sampletest;MODE=MySQL

keycloak:
    url: ${KEYCLOAK_URL:http://keycloak:8080/auth}
    realm: ${KEYCLOAK_REALM:test}
    client_id: ${KEYCLOAK_CLIENT_ID:test}
    oauth: ${KEYCLOAK_OAUTH:true}

---
spring:
  profiles: test

spring.jpa:
    hibernate:
      ddl-auto: create-drop

keycloak:
    url: ${KEYCLOAK_URL:http://localhost:8080/auth}
    realm: ${KEYCLOAK_REALM:test}
    client_id: ${KEYCLOAK_CLIENT_ID:test}
    oauth: ${KEYCLOAK_OAUTH:true}

---
spring:
  profiles: local

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1/${MYSQL_TODO_DB:tododb}
  username: ${MYSQL_TODO_USER:todo}
  password: ${MYSQL_TODO_PASSWORD:todo}

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update

keycloak:
    url: ${KEYCLOAK_URL:http://keycloak:8080/auth}
    realm: ${KEYCLOAK_REALM:test}
    client_id: ${KEYCLOAK_CLIENT_ID:test}
    oauth: ${KEYCLOAK_OAUTH:true}

